(seq ((seq ((symb 'lambda) (seq ((symb ,t2464)))
                           (seq ((symb 'list) (symb ,t2464)
                                              (seq ((symb 'list) (seq ((symb 'quote) (symb 'quote)))
                                                                 (symb ,t2464)))))))
      (seq ((symb 'quote)
            (seq ((symb 'lambda)
                  (seq ((symb ,t2464)))
                  (seq ((symb 'list) (symb ,t2464)
                                     (seq ((symb 'list) (seq ((symb 'quote) (symb 'quote)))
                                                        (symb ,t2464)))))))))))
